# Generated by Django 5.1.7 on 2025-03-20 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_reciperequirements_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeRequirements',
            new_name='RecipeRequirement',
        ),
    ]
