# Generated by Django 5.1.7 on 2025-03-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_reciperequirements_reciperequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('grams', 'g'), ('pounds', 'lbs'), ('cup', 'c'), ('kilogram', 'kg'), ('tablespoon', 'tbsp'), ('teaspoon', 'tsp'), ('millimeter', 'ml'), ('ounces', 'oz'), ('other', '')], default='other', max_length=10),
        ),
    ]
