# Generated by Django 5.1.7 on 2025-03-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='custom_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
