# Generated by Django 5.1.7 on 2025-03-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_ingredient_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='custom_unit',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
        migrations.AddField(
            model_name='reciperequirement',
            name='custom_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reciperequirement',
            name='unit',
            field=models.CharField(blank=True, choices=[('grams', 'g'), ('pounds', 'lbs'), ('cup', 'c'), ('kilogram', 'kg'), ('tablespoon', 'tbsp'), ('teaspoon', 'tsp'), ('millimeter', 'ml'), ('ounces', 'oz'), ('other', '-')], max_length=10, null=True),
        ),
    ]
