# Generated by Django 5.1.7 on 2025-03-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_ingredient_custom_unit_remove_ingredient_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='purchases',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
